# Use Java base image
FROM openjdk:21-slim

# Set working directory
WORKDIR /app

# Copy wrapper files and make mvnw executable
COPY mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN ./mvnw dependency:go-offline

# Copy the rest of the backend source
COPY . .

# Build the Spring Boot JAR
RUN ./mvnw clean package -DskipTests

# Run the application
CMD ["java", "-jar", "target/Time-Table-Management-0.0.1-SNAPSHOT.jar"]
